### ISSUE TITLE
Arc thread share

### ISSUE THREAD

**Issue by francois-pasquier** [Mange/mpris-rs#42]
Is there any way to share an instance of PlayerFinder accross threads ?
I tried using std::sync::Arc but it seems I can't use it with this lib ?

Should I just create multiple instances of PlayerFinder ?
I have one running in order to get the events but I need to call actions like play/pause on another thread.

**Comment by Mange** [comment]
You could put it in a Murex, maybe. But I think sharing Player instances is better than sharing a finder.
You could also have a dedicated thread for the players and send messages to a queue that other threads can consume.

**Comment by francois-pasquier** [comment]
> You could also have a dedicated thread for the players and send messages to a queue that other threads can consume.

It might be just what I need, thank you
