### ISSUE TITLE
2.0.0-rc2 seems to not generate an event of any kind when the currently playing track changes

### ISSUE THREAD

**Issue by Kilobyte22** [Mange/mpris-rs#51]
This problem seems to only occur after upgrading the the current release candidate (also tested with master), the very same code worked on version 1.1.2.

Minimal non-working example:
```rust
use mpris::PlayerFinder;

fn main() {
    let finder = PlayerFinder::new().unwrap();
    let player = finder.find_active().unwrap();

    for event in player.events().unwrap() {
        println!("Got event: {:?}", event);
    }
}
```

Run, then skip to next track.

Expected Behaviour: Output along the lines of `Got event: Ok(TrackChanged(Metadata { ... } ))`  
Actual Behaviour: No output.

**Comment by Kilobyte22** [comment]
I have further investigated this issue. This is actually related to Spotify in particular, which actually violates the MPRIS specification. In particular this library detects the change of track metadata by looking at the TrackID. This is sensible and would work, however Spotify does not actually use a correct D-Bus path for the track id, so `Metadata::track_id` returns `None`. This leads to the `PlayerEvents` iterator not detecting a change in track, as both the old and the new `Option<TrackID>`s are `None`. Since Spotify is a relatively commonly used Player, i would suggest adding a second parameter to the check - URL seems like a reasonable fit.

I have implemented this workaround in #52.

I have no idea however why this issue did not occur earlier - i could not identify any change in this library nor in dbus-rs that could have caused this.

**Comment by Mange** [comment]
Hmm, that's very curious. I wonder if bisecting commits could find where this broke, but then again it could also be a Spotify update breaking this.

I like the workaround you presented and will merge it shortly.

**Comment by Kilobyte22** [comment]
I tested this with the same instance of Spotify while testing the example above, so it's very likely not a Spotify update.
