### ISSUE TITLE
Functionality to retrieve the unique part of a player's bus name?

### ISSUE THREAD

**Issue by InputUsername** [Mange/mpris-rs#53]
Hi, I'm developing [a tool](/InputUsername/rescrobbled) that uses `mpris-rs`, and recently I've run into an issue where my tool identifies music players by their MPRIS identity, whereas other tools (eg. [playerctl](/altdesktop/playerctl)) extract the name from the player's bus name. This results for example in a player reporting as "Spotify" (MPRIS identity) vs "spotify" (the unique part of the bus name `org.mpris.MediaPlayer2.spotify`). Obviously extracting this name is trivial, but I thought it might make sense to add it to `mpris-rs` for ease of use. What are your thoughts?

Thank you for maintaining this great library!

**Comment by Mange** [comment]
Sure thing, a PR for this would be welcome.

But I don't really understand why the player's identity property doesn't work for you.

**Comment by InputUsername** [comment]
Alright, PR coming up.

I'm not sure why it's needed either. Playerctl apparently identifies players by their bus name instead of the identity property. One of my users wanted to be able to use playerctl's list of player names to whitelist music players with my application. The identity property differs from the bus name for some players, so this didn't work before.

It's a minor thing, but I thought it could be useful to include in `mpris-rs`.

**Comment by Mange** [comment]
Sounds reasonable. I was mainly wondering if it would be better to expose the whole thing instead since it might be so app-specific to want that specific part.

Maybe both?

I'll have a look at your PR the next time I'm at my computer

**Comment by Mange** [comment]
Fixed now in `master`.
