### ISSUE TITLE
"NOTE: Until it is possible to mark a minimum Rust version..."

### ISSUE THREAD

**Issue by ssokolow** [Mange/mpris-rs#67]
As of Cargo 1.56.0, [it is possible](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field):

> The `rust-version` field is an optional key that tells cargo what version of the Rust language and compiler your package can be compiled with. If the currently selected version of the Rust compiler is older than the stated version, cargo will exit with an error, telling the user what version is required.
> 
> The first version of Cargo that supports this field was released with Rust 1.56.0. In older releases, the field will be ignored, and Cargo will display a warning.
> 
> ```toml
> [package]
> # ...
> rust-version = "1.56"
> ```
> 
> The Rust version must be a bare version number with two or three components; it cannot include semver operators or pre-release identifiers. Compiler pre-release identifiers such as -nightly will be ignored while checking the Rust version. The `rust-version` must be equal to or newer than the version that first introduced the configured `edition`.
> 
> The `rust-version` may be ignored using the `--ignore-rust-version` option.
> 
> Setting the `rust-version` key in `[package]` will affect all targets/crates in the package, including test suites, benchmarks, binaries, examples, etc.

**Comment by Mange** [comment]
Thanks! I'll keep this in mind. :heart:

**Comment by ssokolow** [comment]
Happy to help. :)

I haven't tried it myself, but there's also [cargo-msrv](https://github.com/foresterre/cargo-msrv) for identifying, verifying, or listing MSRVs.

**Comment by Mange** [comment]
This is now in use for the 2.0.0 release. Thank you very much!
