### ISSUE TITLE
Player::get_track_list fails with Spotify

### ISSUE THREAD

**Issue by fufexan** [Mange/mpris-rs#70]
I've tried testing [the ProgressTracker example](https://github.com/Mange/mpris-rs/blob/master/examples/progress_tracker.rs) to adapt it to output json eventually, but I get a panic when trying to run it:
`thread 'main' panicked at 'D-Bus call failed: Failed to call method'`

It seems to fail on `player.track_progress()`. I've dug through the code and, a few functions deep, found that the culprit is `get_track_list()`.

This only happens for Spotify afaict. I've tried YouTube on Firefox and `ncspot`, and these don't seem to have the issue. Perhaps Spotify incorrectly reports the existence of `org.mpris.MediaPlayer2.TrackList`?

**Comment by Mange** [comment]
Does it behave differently when playing from a real saved playlist vs something more etherial, like a "Radio" / auto-playing after playlist end, vs non-playlist playlists like albums, podcasts, etc.?

**Comment by fufexan** [comment]
No. Any song played gives the same error.
