### ISSUE TITLE
Handle `Metadata.length()` being a string

### ISSUE THREAD

**Issue by ravener** [Mange/mpris-rs#82]
Some players seem to put the microseconds length as a string, I've seen this with Amberol so far:

```
Metadata { values: {"xesam:title": String("Crazy On Emotion"), "mpris:length": String("239000000"), "xesam:album": String("Super Eurobeat 218"), "xesam:artist": Array([String("Ace")])} }
```

This fails parsing with `Metadata.length()` function because it does not consider strings, it'd be great to handle them too and attempt to convert strings to a number.

**Comment by ravener** [comment]
Technically speaking though, this may go against the spec, maybe we should instead report this upstream so Amberol switches to using an integer?

Edit: After digging deeper into their code, it seems to use a crate named `mpris-player` and it seems to store the length as `i64` but then all of a sudden decides to serialize it as a string??? [See this file](https://gitlab.gnome.org/World/Rust/mpris-player/-/blob/master/src/metadata.rs?ref_type=heads#L28)

It also seems like that crate is no longer maintained, so Amberol is just using a deprecated crate to report mpris status. I guess it's better to report this upstream.

Update: I reported an upstream issue so let's see what happens https://gitlab.gnome.org/World/amberol/-/issues/380

**Comment by Mange** [comment]
Thank you for reporting upstream. I prefer being spec compliant here, unless this turns out to be a widespread problem. So far I've never seen this before, and after reading the upstream big report I feel confident in this being a mistake that should be fixed on their end.
